# environments/dev/apps/nginx-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/ibrahimbakayoko/GitOpsOpenSourceLab.git
    path: app/nginx
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
