apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-dev
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/ibrahimbakayoko/GitOpsOpenSourceLab.git
    targetRevision: main
    path: environnement/dev/app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
