apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/ibrahimbakayoko/GitOpsOpenSourceLab.git
    targetRevision: main
    path: environment/prod/app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}   # pas d'auto-sync en prod, sync manuelle depuis l'UI ArgoCD
