apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: "Projet ArgoCD pour l'environnement de développement"
  
  sourceRepos:
    - https://github.com/tonuser/gitops-lab.git
  
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
